In [220]:
#Some imports
import numpy as np
import matplotlib.pyplot as plt
import random
import queue
import time
from IPython.display import clear_output

#Functions that will be very useful for creating/updating mazes

'''
Define the grid to be working with

**inputs:
dim = dimension size of the grid
n = number of mines

**returns:
board = the grid to be worked with
'''

def environment(dim, n):
    #start with a dim by dim zero array
    
    board = np.zeros((dim,dim))
    
    while n > 0:
        i = random.randint(0, dim - 1)
        j = random.randint(0, dim - 1)
        
        if board[i][j] == 9:
            pass
        else:
            board[i][j] = 9
            n -= 1
            
    for i in range(0, dim):
        for j in range(0, dim):
            if board[i][j] == 9:
                continue
            
            #check all the neighbors
            mines = 0
            rightValid = False
            leftValid = False
            upValid = False
            downValid = False
            if j - 1 >= 0:
                leftValid = True
            if j + 1 < len(board):
                rightValid = True
            if i + 1 < len(board):
                downValid = True
            if i - 1 >= 0:
                upValid = True
        
            #check left
            if leftValid == True:
                #check left adjacent
                if board[i][j-1] == 9:
                    #mine is here
                    mines += 1
                else:
                    #no mine is here
                    pass
                #check left & up
                if upValid == True:
                    if board[i-1][j-1] == 9:
                        #mine is here
                        mines += 1
                    else:
                        #no mine is here
                        pass           
                #check left & down
                if downValid == True:
                    if board[i+1][j-1] == 9:
                        #mine is here
                        mines += 1
                    else:
                        #no mine is here
                        pass
                        
            #check right
            if rightValid == True:
                #check right adjacent
                if board[i][j+1] == 9:
                    #mine is here
                    mines += 1
                else:
                    #no mine is here
                    pass
                #check right & up
                if upValid == True:
                    if board[i-1][j+1] == 9:
                        #mine is here
                        mines += 1
                    else:
                        #no mine is here
                        pass
                #check right & down
                if downValid == True:
                    if board[i+1][j+1] == 9:
                        #mine is here
                        mines += 1
                    else:
                        #no mine is here
                        pass
                        
            #check up adjacent
            if upValid == True:
                if board[i-1][j] == 9:
                    #mine is here
                    mines += 1
                else:
                    #no mine is here
                    pass
                    
            #check down adjacent
            if downValid == True:
                if board[i+1][j] == 9:
                    #mine is here
                    mines += 1
                else:
                    #no mine is here
                    pass
            
            board[i][j] = mines
    
    return board


'''
A Method to Check the Neighbors of a Cell

**inputs:
possible_moves = array of coordinates for the remaining moves
coord = tuple containing the coordinates

**returns:
neighbors = the list of neighbors for the given coordinate
'''

#feed in the checking function the remaining possible moves, and it will easily return the neighbors
def checkNeighbors(possible_moves, coord):
    neighbors = []
    i = coord[0]
    j = coord[1]
    
    if (i+1, j) in possible_moves:
        neighbors.append((i+1, j))
        
    if (i-1, j) in possible_moves:
        neighbors.append((i-1, j))
        
    if (i, j+1) in possible_moves:
        neighbors.append((i, j+1))
        
    if (i, j-1) in possible_moves:
        neighbors.append((i, j-1))
                          
    if (i+1, j+1) in possible_moves:
        neighbors.append((i+1, j+1))
                          
    if (i-1, j-1) in possible_moves:
        neighbors.append((i-1, j-1))
                          
    if (i+1, j-1) in possible_moves:
        neighbors.append((i+1, j-1))
                          
    if (i-1, j+1) in possible_moves:
        neighbors.append((i-1, j+1))
        
    return neighbors

'''
A Method to Update the Agent Board

**inputs:
coord = tuple containing the coordinates
main_board = the main board
agent_board = the agent board

**returns:
agent_board = the grid to be worked with
coord = tuple containing the coordinates
clue = number of adjacent mines
'''

def updateBoard(coord, main_board, agent_board):
    i = coord[0]
    j = coord[1]
    agent_board[i][j] = main_board[i][j]
    clue = agent_board[i][j]
    return agent_board, coord, clue

'''
A Method to Check the Number of Uncovered Mines for a Cell

**inputs:
board = the agent board
coord = tuple containing the coordinates

**returns:
mines = the number of neighboring mines
'''

def checkMines(board,coord): 
    #check all the neighbors
    mines = 0
    i = coord[0]
    j = coord[1]
    rightValid = False
    leftValid = False
    upValid = False
    downValid = False
    if j - 1 >= 0:
        leftValid = True
    if j + 1 < len(board):
         rightValid = True
    if i + 1 < len(board):
         downValid = True
    if i - 1 >= 0:
        upValid = True
        
    #check left
    if leftValid == True:
        #check left adjacent
        if int(board[i][j-1]) == 9 or board[i][j-1] == 0.5:
            #mine is here
            mines += 1
        else:
            #no mine is here
            pass
        #check left & up
        if upValid == True:
            if int(board[i-1][j-1]) == 9 or board[i-1][j-1] == 0.5:
                #mine is here
                mines += 1
            else:
                #no mine is here
                pass           
        #check left & down
        if downValid == True:
            if int(board[i+1][j-1]) == 9 or board[i+1][j-1] == 0.5:
                #mine is here
                mines += 1
            else:
                #no mine is here
                pass
                        
    #check right
    if rightValid == True:
        #check right adjacent
        if int(board[i][j+1]) == 9 or board[i][j+1] == 0.5:
            #mine is here
            mines += 1
        else:
            #no mine is here
            pass
        #check right & up
        if upValid == True:
            if int(board[i-1][j+1]) == 9 or board[i-1][j+1] == 0.5:
                 #mine is here
                mines += 1
            else:
                #no mine is here
                pass
        #check right & down
        if downValid == True:
            if int(board[i+1][j+1]) == 9 or board[i+1][j+1] == 0.5:
                #mine is here
                mines += 1
            else:
                #no mine is here
                pass
                        
    #check up adjacent
    if upValid == True:
        if int(board[i-1][j]) == 9 or board[i-1][j] == 0.5:
            #mine is here
            mines += 1
        else:
            #no mine is here
            pass
                    
    #check down adjacent
    if downValid == True:
        if int(board[i+1][j]) == 9 or board[i+1][j] == 0.5:
            #mine is here
            mines += 1
        else:
            #no mine is here
            pass
            
    return mines

In [221]:
'''
The Actual Game to be Played by our Agent

***********************NO INPUTS****************************

**inputs:
dim = dimension size of the grid
n = number of mines

**returns:

'''

def MinesweeperNInputs(dim, n):
    
    #create our main board and the board the agent will see
    main_board = environment(dim, n)
    agent_board = environment(dim, 0) + 11
    print(main_board)

    #our three fringes, which make up our general knowledge base
    mineFringe = []
    safeFringe = []
    KB = []

    #populate a list of all the possible moves we can make, which will keep track of moves that can be made
    possible_moves = []
    for i in range(0, dim):
        for j in range(0, dim):
            possible_moves.append((i, j))

    
    #play until we finish the game
    gameFinished = False
    while gameFinished == False:
        
        #our terminating condition
        if len(possible_moves)==0: 
            gameFinished=True
            
            clear_output()
            
            print("Agent's Board:")
            print(agent_board)
            print("The Actual Board:")
            print(main_board)
            return 
        
        else:  
            
            '''
            #CHECK THE MINE FRINGE
            '''
            
            #if nothing in the mine fringe pass to next step
            if len(mineFringe) == 0:
                pass
            
            #immediately flag things in mine fringe
            else:
                
                #go through the mineFringe and flag spots until the fringe is empty again
                while len(mineFringe) != 0:
                    
                    #show the recommended move
                    print("recommended mine at:", (mineFringe[0][0], mineFringe[0][1]))
                    
                    #flag a spot with 0.5
                    agent_board[mineFringe[0][0]][mineFringe[0][1]] = 0.5
                    
                    #remove from possible moves and mine fringe
                    possible_moves.remove(mineFringe[0])
                    mineFringe.remove(mineFringe[0])
                    
                    #show the updated board
                    print(agent_board)
                    time.sleep(2)
                    
                #restarts main while loop from beginning
                continue

            '''
            #CHECK THE SAFE FRINGE
            '''
            
            #if nothing in the safe fringe pass to next step
            if len(safeFringe) == 0:
                pass
            
            #immediately open things in safe fringe
            else:
                
                #go through the safeFringe and open spots until the fringe is empty again
                while len(safeFringe) != 0:
                    
                    #if the move has already been made
                    if not(safeFringe[0] in possible_moves):
                        safeFringe.remove(safeFringe[0])
                        continue
                        
                    #show the recommened move
                    print("recommended safe move at:", (safeFringe[0][0], safeFringe[0][1]))
                    i = safeFringe[0][0]
                    j = safeFringe[0][1]
                    
                    #open a spot if it is in the safe fringe
                    agent_board, coord, clue = updateBoard((i,j), main_board, agent_board)
                    
                    #add move to KB, then remove from possible moves and mine fringe
                    KB.append([coord, clue, len(checkNeighbors(possible_moves, coord))])
                    possible_moves.remove(safeFringe[0])
                    safeFringe.remove(safeFringe[0])
                    
                    #show the updated board
                    print(agent_board)
                    time.sleep(2)
                    
                #restarts main while loop from beginning
                continue

            '''
            #CHECK THE KNOWLEDGE BASE
            '''
            
            #if nothing in the KB pass to next step
            if len(KB) == 0:
                pass
            
            #look through our KB for moves to add to safe fringe or mine fringe
            else:
                #make a list for things to be removed from KB
                to_be_removed = []
                for item in range(0, len(KB)):
                    
                    #updates the value of adjacent neighbors in the KB
                    KB[item][2] = len(checkNeighbors(possible_moves, KB[item][0]))
                    
                    #checks if all the mines have been found for a clue already; if so prepare to remove from KB
                    if KB[item][1] != 0 and checkMines(agent_board, KB[item][0]) == int(KB[item][1]):
                        
                        #add the moves to safe fringe and get ready for removal
                        safeFringe += checkNeighbors(possible_moves, KB[item][0])
                        to_be_removed.append(KB[item])
                        
                    
                #if there are things to be removed, remove them
                if len(to_be_removed) > 0:
                    while len(to_be_removed) > 0:
                        i = 0
                        while i < len(KB):
                            
                            #find the thing to be removed in KB
                            if to_be_removed[0][0] == KB[i][0]:
                                KB.remove(KB[i])
                                to_be_removed.remove(to_be_removed[0])
                                break
                            else:
                                i += 1
                    
                    #restarts main while loop from beginning
                    continue
                    
                    
                
                check = False
                #check each item in the KB
                for item in KB:
                    #if clue is 0 all neighbors are safe
                    if item[1] == 0: 
                        x = item
                        safeFringe += checkNeighbors(possible_moves, x[0]) 
                        check = True
                        break
                
                
                    #if number of neighbors is equal to clue, all are mines 
                    elif item[1] - checkMines(agent_board, item[0]) == item[2]: 
                        x = item
                        mineFringe += checkNeighbors(possible_moves, x[0]) 
                        check = True
                        break 
                    
                    #if neither of the two above things, don't do anything
                    else:
                        pass
                    
                        
                #only remove from KB if we added something to mine or safe fringe
                if check == True:
                    KB.remove(x)
                    continue
                
            '''
            #RANDOMPICK (LAST RESORT)
            '''
            
            #pick a random coordinate from the remaining possible moves
            x = random.randint(0,len(possible_moves) - 1)
            
            #show the recommended move
            print("recommended random move: ", possible_moves[x])
            i = possible_moves[x][0]
            j = possible_moves[x][1]
            
            #open the random spot
            agent_board, coord, clue = updateBoard((i,j), main_board, agent_board)
            
            #if the spot we hit was a mine tell the user and keep going, no need to add to KB
            if clue==9:
                print('MINE HIT AT:',coord)
            
            #otherwise add to KB
            else:
                KB.append([coord, clue, len(checkNeighbors(possible_moves, coord))])
            
            #remove from possible moves
            possible_moves.remove(coord)
            print(agent_board)
            time.sleep(2)
            
    return

In [222]:
MinesweeperNInputs(5,10)

Agent's Board:
[[0.5 0.5 2.  2.  0.5]
 [3.  5.  9.  4.  2. ]
 [9.  4.  0.5 0.5 2. ]
 [1.  4.  9.  9.  2. ]
 [0.  2.  0.5 3.  1. ]]
The Actual Board:
[[9. 9. 2. 2. 9.]
 [3. 5. 9. 4. 2.]
 [9. 4. 9. 9. 2.]
 [1. 4. 9. 9. 2.]
 [0. 2. 9. 3. 1.]]


In [116]:
'''
a = environment(10, 20)
b = environment(10, 0)
print(a)
print()
print(b)
c = np.zeros((10,10))
for i in range(0, 10):
    for j in range(0, 10):
        c[i][j] = '*'

print(c)
'''

[[9. 1. 0. 0. 0. 1. 9. 3. 2. 1.]
 [2. 2. 1. 0. 0. 1. 2. 9. 9. 1.]
 [1. 9. 2. 1. 1. 1. 2. 3. 2. 1.]
 [3. 3. 4. 9. 2. 2. 9. 2. 0. 0.]
 [9. 9. 3. 9. 2. 2. 9. 4. 2. 1.]
 [2. 2. 2. 1. 1. 1. 2. 9. 9. 1.]
 [0. 0. 1. 1. 1. 0. 1. 3. 3. 2.]
 [0. 0. 1. 9. 2. 1. 1. 2. 9. 2.]
 [2. 2. 2. 1. 2. 9. 2. 3. 9. 2.]
 [9. 9. 1. 0. 1. 2. 9. 2. 1. 1.]]

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


ValueError: could not convert string to float: '*'

In [58]:
'''
****potentially for visuals*****


print('hi!')
time.sleep(2)
clear_output()
'''

In [214]:
'''
The Actual Game to be Played by our Agent

***********************INPUTS****************************

**inputs:
dim = dimension size of the grid
n = number of mines

**returns:

'''

def MinesweeperInputs(dim, n):
    
    #create our main board and the board the agent will see
    main_board = environment(dim, n)
    agent_board = environment(dim, 0) + 11
    print(main_board)

    #our three fringes, which make up our general knowledge base
    mineFringe = []
    safeFringe = []
    KB = []

    #populate a list of all the possible moves we can make, which will keep track of moves that can be made
    possible_moves = []
    for i in range(0, dim):
        for j in range(0, dim):
            possible_moves.append((i, j))

    
    #play until we finish the game
    gameFinished = False
    while gameFinished == False:
        
        #our terminating condition
        if len(possible_moves)==0: 
            gameFinished=True
            
            clear_output()
            
            print("Agent's Board:")
            print(agent_board)
            print("The Actual Board:")
            print(main_board)
            return
        
        else:  
            
            '''
            #CHECK THE MINE FRINGE
            '''
            
            #if nothing in the mine fringe pass to next step
            if len(mineFringe) == 0:
                pass
            
            #immediately flag things in mine fringe
            else:
                
                #go through the mineFringe and flag spots until the fringe is empty again
                while len(mineFringe) != 0:
                    
                    #take an input from the user
                    print("recommended mine at:", (mineFringe[0][0], mineFringe[0][1]))
                    i = int(input())
                    j = int(input())
                    
                    #flag a spot with 0.5
                    agent_board[i][j] = 0.5
                    
                    #remove from possible moves and mine fringe
                    possible_moves.remove(mineFringe[0])
                    mineFringe.remove(mineFringe[0])
                    
                    #show the updated board
                    print(agent_board)
                    
                #restarts main while loop from beginning
                continue

            '''
            #CHECK THE SAFE FRINGE
            '''
            
            #if nothing in the safe fringe pass to next step
            if len(safeFringe) == 0:
                pass
            
            #immediately open things in safe fringe
            else:
                
                #go through the safeFringe and open spots until the fringe is empty again
                while len(safeFringe) != 0:
                    
                    #if the move has already been made
                    if not(safeFringe[0] in possible_moves):
                        safeFringe.remove(safeFringe[0])
                        continue
                        
                    #take an input from the user
                    print("recommended safe move at:", (safeFringe[0][0], safeFringe[0][1]))
                    i = int(input())
                    j = int(input())
                    
                    #open a spot if it is in the safe fringe
                    agent_board, coord, clue = updateBoard((i,j), main_board, agent_board)
                    
                    #add move to KB, then remove from possible moves and mine fringe
                    KB.append([coord, clue, len(checkNeighbors(possible_moves, coord))])
                    possible_moves.remove(safeFringe[0])
                    safeFringe.remove(safeFringe[0])
                    
                    #show the updated board
                    print(agent_board)
                    
                #restarts main while loop from beginning
                continue

            '''
            #CHECK THE KNOWLEDGE BASE
            '''
            
            #if nothing in the KB pass to next step
            if len(KB) == 0:
                pass
            
            #look through our KB for moves to add to safe fringe or mine fringe
            else:
                #make a list for things to be removed from KB
                to_be_removed = []
                for item in range(0, len(KB)):
                    
                    #updates the value of adjacent neighbors in the KB
                    KB[item][2] = len(checkNeighbors(possible_moves, KB[item][0]))
                    
                    #checks if all the mines have been found for a clue already; if so prepare to remove from KB
                    if KB[item][1] != 0 and checkMines(agent_board, KB[item][0]) == int(KB[item][1]):
                        
                        #add the moves to safe fringe and get ready for removal
                        safeFringe += checkNeighbors(possible_moves, KB[item][0])
                        to_be_removed.append(KB[item])
                        
                    
                #if there are things to be removed, remove them
                if len(to_be_removed) > 0:
                    while len(to_be_removed) > 0:
                        i = 0
                        while i < len(KB):
                            
                            #find the thing to be removed in KB
                            if to_be_removed[0][0] == KB[i][0]:
                                KB.remove(KB[i])
                                to_be_removed.remove(to_be_removed[0])
                                break
                            else:
                                i += 1
                    
                    #restarts main while loop from beginning
                    continue
                    
                    
                
                check = False
                #check each item in the KB
                for item in KB:
                    #if clue is 0 all neighbors are safe
                    if item[1] == 0: 
                        x = item
                        safeFringe += checkNeighbors(possible_moves, x[0]) 
                        check = True
                        break
                
                
                    #if number of neighbors is equal to clue, all are mines 
                    elif item[1] - checkMines(agent_board, item[0]) == item[2]: 
                        x = item
                        mineFringe += checkNeighbors(possible_moves, x[0]) 
                        check = True
                        break 
                    
                    #if neither of the two above things, don't do anything
                    else:
                        pass
                    
                        
                #only remove from KB if we added something to mine or safe fringe
                if check == True:
                    KB.remove(x)
                    continue
                
            '''
            #RANDOMPICK (LAST RESORT)
            '''
            
            #pick a random coordinate from the remaining possible moves
            x = random.randint(0,len(possible_moves) - 1)
            
            #take an input from the user
            print("recommended random move: ", possible_moves[x])
            i = int(input())
            j = int(input())
            
            #open the random spot
            agent_board, coord, clue = updateBoard((i,j), main_board, agent_board)
            
            #if the spot we hit was a mine tell the user and keep going, no need to add to KB
            if clue==9:
                print('MINE HIT AT:',coord)
            
            #otherwise add to KB
            else:
                KB.append([coord, clue, len(checkNeighbors(possible_moves, coord))])
            
            #remove from possible moves
            possible_moves.remove(coord)
            print(agent_board)
            
    return

In [215]:
MinesweeperInputs(5,5)

[[0. 2. 9. 2. 0.]
 [0. 2. 9. 2. 0.]
 [0. 1. 1. 2. 1.]
 [1. 2. 2. 2. 9.]
 [1. 9. 9. 2. 1.]]
recommended random move:  (2, 0)


KeyboardInterrupt: 