In [171]:
#Some imports
import numpy as np
import matplotlib.pyplot as plt
import random
import queue
import time

'''
Define the grid to be working with

**inputs:
dim = dimension size of the grid
n = number of mines

**returns:
board = the grid to be worked with
'''

def environment(dim, n):
    #start with a dim by dim zero array
    
    board = np.zeros((dim,dim))
    
    while n > 0:
        i = random.randint(0, dim - 1)
        j = random.randint(0, dim - 1)
        
        if board[i][j] == 9:
            pass
        else:
            board[i][j] = 9
            n -= 1
            
    for i in range(0, dim):
        for j in range(0, dim):
            if board[i][j] == 9:
                continue
            
            #check all the neighbors
            mines = 0
            rightValid = False
            leftValid = False
            upValid = False
            downValid = False
            if j - 1 >= 0:
                leftValid = True
            if j + 1 < len(board):
                rightValid = True
            if i + 1 < len(board):
                downValid = True
            if i - 1 >= 0:
                upValid = True
        
            #check left
            if leftValid == True:
                #check left adjacent
                if board[i][j-1] == 9:
                    #mine is here
                    mines += 1
                else:
                    #no mine is here
                    pass
                #check left & up
                if upValid == True:
                    if board[i-1][j-1] == 9:
                        #mine is here
                        mines += 1
                    else:
                        #no mine is here
                        pass           
                #check left & down
                if downValid == True:
                    if board[i+1][j-1] == 9:
                        #mine is here
                        mines += 1
                    else:
                        #no mine is here
                        pass
                        
            #check right
            if rightValid == True:
                #check right adjacent
                if board[i][j+1] == 9:
                    #mine is here
                    mines += 1
                else:
                    #no mine is here
                    pass
                #check right & up
                if upValid == True:
                    if board[i-1][j+1] == 9:
                        #mine is here
                        mines += 1
                    else:
                        #no mine is here
                        pass
                #check right & down
                if downValid == True:
                    if board[i+1][j+1] == 9:
                        #mine is here
                        mines += 1
                    else:
                        #no mine is here
                        pass
                        
            #check up adjacent
            if upValid == True:
                if board[i-1][j] == 9:
                    #mine is here
                    mines += 1
                else:
                    #no mine is here
                    pass
                    
            #check down adjacent
            if downValid == True:
                if board[i+1][j] == 9:
                    #mine is here
                    mines += 1
                else:
                    #no mine is here
                    pass
            
            board[i][j] = mines
    
    return board

In [172]:
'''
A Method to Check the Neighbors of a Cell

**inputs:
possible_moves = array of coordinates for the remaining moves
i = row
j = column

**returns:
board = the grid to be worked with
'''

#feed in the checking function the remaining possible moves, and it will easily return the neighbors
def checkNeighbors(possible_moves, coord):
    neighbors = []
    i = coord[0]
    j = coord[1]
    
    if (i+1, j) in possible_moves:
        neighbors.append((i+1, j))
        
    if (i-1, j) in possible_moves:
        neighbors.append((i-1, j))
        
    if (i, j+1) in possible_moves:
        neighbors.append((i, j+1))
        
    if (i, j-1) in possible_moves:
        neighbors.append((i, j-1))
                          
    if (i+1, j+1) in possible_moves:
        neighbors.append((i+1, j+1))
                          
    if (i-1, j-1) in possible_moves:
        neighbors.append((i-1, j-1))
                          
    if (i+1, j-1) in possible_moves:
        neighbors.append((i+1, j-1))
                          
    if (i-1, j+1) in possible_moves:
        neighbors.append((i-1, j+1))
        
    return neighbors

In [173]:
def updateBoard(coord, main_board, agent_board):
    i = coord[0]
    j = coord[1]
    agent_board[i][j] = main_board[i][j]
    clue = agent_board[i][j]
    return agent_board, coord, clue

In [174]:
def checkMines(board,coord): 
    #check all the neighbors
    mines = 0
    i = coord[0]
    j = coord[1]
    rightValid = False
    leftValid = False
    upValid = False
    downValid = False
    if j - 1 >= 0:
        leftValid = True
    if j + 1 < len(board):
         rightValid = True
    if i + 1 < len(board):
         downValid = True
    if i - 1 >= 0:
        upValid = True
        
    #check left
    if leftValid == True:
        #check left adjacent
        if int(board[i][j-1]) == 9 or board[i][j-1] == 0.5:
            #mine is here
            mines += 1
        else:
            #no mine is here
            pass
        #check left & up
        if upValid == True:
            if int(board[i-1][j-1]) == 9 or board[i-1][j-1] == 0.5:
                #mine is here
                mines += 1
            else:
                #no mine is here
                pass           
        #check left & down
        if downValid == True:
            if int(board[i+1][j-1]) == 9 or board[i+1][j-1] == 0.5:
                #mine is here
                mines += 1
            else:
                #no mine is here
                pass
                        
    #check right
    if rightValid == True:
        #check right adjacent
        if int(board[i][j+1]) == 9 or board[i][j+1] == 0.5:
            #mine is here
            mines += 1
        else:
            #no mine is here
            pass
        #check right & up
        if upValid == True:
            if int(board[i-1][j+1]) == 9 or board[i-1][j+1] == 0.5:
                 #mine is here
                mines += 1
            else:
                #no mine is here
                pass
        #check right & down
        if downValid == True:
            if int(board[i+1][j+1]) == 9 or board[i+1][j+1] == 0.5:
                #mine is here
                mines += 1
            else:
                #no mine is here
                pass
                        
    #check up adjacent
    if upValid == True:
        if int(board[i-1][j]) == 9 or board[i-1][j] == 0.5:
            #mine is here
            mines += 1
        else:
            #no mine is here
            pass
                    
    #check down adjacent
    if downValid == True:
        if int(board[i+1][j]) == 9 or board[i+1][j] == 0.5:
            #mine is here
            mines += 1
        else:
            #no mine is here
            pass
            
    return mines

In [209]:
'''
The Actual Game to be Played by our Agent

**inputs:
dim = dimension size of the grid
n = number of mines

**returns:

'''

def Minesweeper(dim, n):
    #create our main board and the board the agent will see
    main_board = environment(dim, n)
    agent_board = environment(dim, 0) + 11
    print(main_board)

    #our three fringes, which make up our general knowledge base
    mineFringe = []
    safeFringe = []
    KB = []

    #populate a list of all the possible moves we can make, which will be edited later
    possible_moves = []
    for i in range(0, dim):
        for j in range(0, dim):
            possible_moves.append((i, j))

    #play until we finish the game
    gameFinished = False
    while gameFinished == False:
        if len(possible_moves)==0: 
            gameFinished=True
            return agent_board
        else:  
            '''
            #CHECK THE MINE FRINGE
            #FLAG A SPOT WITH 0.5 IF IT IS IN THE MINE FRINGE, THEN REMOVE IT FROM THE MINE FRINGE AND POSSIBLE_MOVES
            #IF NOTHING IS IN THE MINE FRINGE, PASS
            '''
            if len(mineFringe) == 0:
                pass
            else:
                #go through the mineFringe and flag spots until the fringe is empty again
                while len(mineFringe) != 0:
                    print("recommended mine at:", (mineFringe[0][0], mineFringe[0][1]))
                    i = int(input())
                    j = int(input())
                    agent_board[i][j] = 0.5
                    possible_moves.remove(mineFringe[0])
                    mineFringe.remove(mineFringe[0])
                    print(agent_board)
                #restarts main while loop from beginning
                continue

            '''
            #CHECK THE SAFE FRINGE
            #REVEAL A SPOT AND THEN REMOVE FROM THE SAFE FRINGE AND POSSIBLE_MOVES
            #IF NOTHING IS IN THE SAFE FRINGE, PASS
            '''
            if len(safeFringe) == 0:
                pass
            else:
                #go through the safeFringe and open spots until the fringe is empty again
                while len(safeFringe) != 0:
                    #if the move has already been made
                    if not(safeFringe[0] in possible_moves):
                        safeFringe.remove(safeFringe[0])
                        continue
                        
                    print("recommended safe move at:", (safeFringe[0][0], safeFringe[0][1]))
                    i = int(input())
                    j = int(input())
                    agent_board, coord, clue = updateBoard((i,j), main_board, agent_board)
                    KB.append([coord, clue, len(checkNeighbors(possible_moves, coord))])
                    possible_moves.remove(safeFringe[0])
                    safeFringe.remove(safeFringe[0])
                    print(agent_board)
                #restarts main while loop from beginning
                continue

            '''
            #CHECK THE KNOWLEDGE BASE (KB)
            #IF THE NUMBER OF MINES = THE NUMBER OF ADJACENT CELLS, CHECK THE NEIGHBORS AND ADD TO MINE FRINGE
            #IF THE NUMBER OF MINES = 0, CHECK THE NEIGHBORS AND ADD TO SAFE FRINGE
            #IF KB IS EMPTY, PASS
            #NO NEED TO USE CHECK NEIGHBOR FUNCTION HERE UNLESS WE ARE SURE TO ADD IT TO EITHER SAFE OR MINE FRINGE
            
            *******NEED TO IMPLEMENT A WAY OF UPDATING THINGS ALREADY IN THE KB ONCE A NEIGHBOR IS OPENED*********
            '''
            if len(KB) == 0:
                pass
            else:
                to_be_removed = []
                for item in range(0, len(KB)):
                    #updates the value of adjacent neighbors
                    KB[item][2] = len(checkNeighbors(possible_moves, KB[item][0]))
                    
                    #checks if all the mines have been found for a clue already; if so prepare to remove from KB
                    if KB[item][1] != 0 and checkMines(agent_board, KB[item][0]) == int(KB[item][1]):
                        #going to have double counting... make sure to account for it in safeFringe
                        safeFringe += checkNeighbors(possible_moves, KB[item][0])
                        to_be_removed.append(KB[item])
                        
                    
                
                if len(to_be_removed) > 0:
                    while len(to_be_removed) > 0:
                        i = 0
                        while i < len(KB):
                            if to_be_removed[0][0] == KB[i][0]:
                                KB.remove(KB[i])
                                to_be_removed.remove(to_be_removed[0])
                                break
                            else:
                                i += 1
                    continue
                    
                    
                    
                check = False
                #check each item in the KB
                for item in KB:
                    #if clue is 0 all neighbors are safe
                    if item[1] == 0: 
                        x = item
                        safeFringe += checkNeighbors(possible_moves, x[0]) 
                        check = True
                        break
                
                
                    #if number of neighbors is equal to clue, all are mines 
                    elif item[1] - checkMines(agent_board, item[0]) == item[2]: 
                        x = item
                        mineFringe += checkNeighbors(possible_moves, x[0]) 
                        check = True
                        break 
                    
                    else:
                        pass
                    
                        
                #remove from KB but don't need to remove from possible_moves since we already did
                if check == True:
                    KB.remove(x)
                    continue
                
            '''
            #RANDOMPICK (OUR LAST RESORT)
            '''
            x = random.randint(0,len(possible_moves) - 1)
            print("recommended random move: ", possible_moves[x])
            i = int(input())
            j = int(input())
            agent_board, coord, clue = updateBoard((i,j), main_board, agent_board)
            
            if clue==9:
                print('MINE HIT AT:',coord)
            else:
                KB.append([coord, clue, len(checkNeighbors(possible_moves, coord))])
            
            possible_moves.remove(coord)
            print(agent_board)
            

    #NOT SURE WHAT WE WOULD RETURN HERE YET, IDEALLY WE WILL HAVE VISUALS ALONG THE WAY
    print(agent_board)
    print(main_board)
    return 

In [ ]:
Minesweeper(5,10)

In [116]:
a = environment(10, 20)
b = environment(10, 0)
print(a)
print()
print(b)
c = np.zeros((10,10))
for i in range(0, 10):
    for j in range(0, 10):
        c[i][j] = '*'

print(c)

[[9. 1. 0. 0. 0. 1. 9. 3. 2. 1.]
 [2. 2. 1. 0. 0. 1. 2. 9. 9. 1.]
 [1. 9. 2. 1. 1. 1. 2. 3. 2. 1.]
 [3. 3. 4. 9. 2. 2. 9. 2. 0. 0.]
 [9. 9. 3. 9. 2. 2. 9. 4. 2. 1.]
 [2. 2. 2. 1. 1. 1. 2. 9. 9. 1.]
 [0. 0. 1. 1. 1. 0. 1. 3. 3. 2.]
 [0. 0. 1. 9. 2. 1. 1. 2. 9. 2.]
 [2. 2. 2. 1. 2. 9. 2. 3. 9. 2.]
 [9. 9. 1. 0. 1. 2. 9. 2. 1. 1.]]

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


ValueError: could not convert string to float: '*'

In [58]:
from IPython.display import clear_output
print('hi!')
time.sleep(2)
clear_output()

In [210]:
'''
The Actual Game to be Played by our Agent

**inputs:
dim = dimension size of the grid
n = number of mines

**returns:

'''

def Minesweeper(dim, n):
    #create our main board and the board the agent will see
    main_board = environment(dim, n)
    agent_board = environment(dim, 0) + 11
    print(main_board)

    #our three fringes, which make up our general knowledge base
    mineFringe = []
    safeFringe = []
    KB = []

    #populate a list of all the possible moves we can make, which will be edited later
    possible_moves = []
    for i in range(0, dim):
        for j in range(0, dim):
            possible_moves.append((i, j))

    #play until we finish the game
    gameFinished = False
    while gameFinished == False:
        if len(possible_moves)==0: 
            gameFinished=True
            return agent_board
        else:  
            '''
            #CHECK THE MINE FRINGE
            #FLAG A SPOT WITH 0.5 IF IT IS IN THE MINE FRINGE, THEN REMOVE IT FROM THE MINE FRINGE AND POSSIBLE_MOVES
            #IF NOTHING IS IN THE MINE FRINGE, PASS
            '''
            if len(mineFringe) == 0:
                pass
            else:
                #go through the mineFringe and flag spots until the fringe is empty again
                while len(mineFringe) != 0:
                    print("recommended mine at:", (mineFringe[0][0], mineFringe[0][1]))
                    i = int(input())
                    j = int(input())
                    agent_board[i][j] = 0.5
                    possible_moves.remove(mineFringe[0])
                    mineFringe.remove(mineFringe[0])
                    print(agent_board)
                #restarts main while loop from beginning
                continue

            '''
            #CHECK THE SAFE FRINGE
            #REVEAL A SPOT AND THEN REMOVE FROM THE SAFE FRINGE AND POSSIBLE_MOVES
            #IF NOTHING IS IN THE SAFE FRINGE, PASS
            '''
            if len(safeFringe) == 0:
                pass
            else:
                #go through the safeFringe and open spots until the fringe is empty again
                while len(safeFringe) != 0:
                    #if the move has already been made
                    if not(safeFringe[0] in possible_moves):
                        safeFringe.remove(safeFringe[0])
                        continue
                        
                    print("recommended safe move at:", (safeFringe[0][0], safeFringe[0][1]))
                    i = int(input())
                    j = int(input())
                    agent_board, coord, clue = updateBoard((i,j), main_board, agent_board)
                    KB.append([coord, clue, len(checkNeighbors(possible_moves, coord))])
                    possible_moves.remove(safeFringe[0])
                    safeFringe.remove(safeFringe[0])
                    print(agent_board)
                #restarts main while loop from beginning
                continue

            '''
            #CHECK THE KNOWLEDGE BASE (KB)
            #IF THE NUMBER OF MINES = THE NUMBER OF ADJACENT CELLS, CHECK THE NEIGHBORS AND ADD TO MINE FRINGE
            #IF THE NUMBER OF MINES = 0, CHECK THE NEIGHBORS AND ADD TO SAFE FRINGE
            #IF KB IS EMPTY, PASS
            #NO NEED TO USE CHECK NEIGHBOR FUNCTION HERE UNLESS WE ARE SURE TO ADD IT TO EITHER SAFE OR MINE FRINGE
            
            *******NEED TO IMPLEMENT A WAY OF UPDATING THINGS ALREADY IN THE KB ONCE A NEIGHBOR IS OPENED*********
            '''
            if len(KB) == 0:
                pass
            else:
                to_be_removed = []
                for item in range(0, len(KB)):
                    #updates the value of adjacent neighbors
                    KB[item][2] = len(checkNeighbors(possible_moves, KB[item][0]))
                    
                    #checks if all the mines have been found for a clue already; if so prepare to remove from KB
                    if KB[item][1] != 0 and checkMines(agent_board, KB[item][0]) == int(KB[item][1]):
                        #going to have double counting... make sure to account for it in safeFringe
                        safeFringe += checkNeighbors(possible_moves, KB[item][0])
                        to_be_removed.append(KB[item])
                        
                    
                
                if len(to_be_removed) > 0:
                    while len(to_be_removed) > 0:
                        i = 0
                        while i < len(KB):
                            if to_be_removed[0][0] == KB[i][0]:
                                KB.remove(KB[i])
                                to_be_removed.remove(to_be_removed[0])
                                break
                            else:
                                i += 1
                    continue
                    
                    
                    
                check = False
                #check each item in the KB
                for item in KB:
                    #if clue is 0 all neighbors are safe
                    if item[1] == 0: 
                        x = item
                        safeFringe += checkNeighbors(possible_moves, x[0]) 
                        check = True
                        break
                
                
                    #if number of neighbors is equal to clue, all are mines 
                    elif item[1] - checkMines(agent_board, item[0]) == item[2]: 
                        x = item
                        mineFringe += checkNeighbors(possible_moves, x[0]) 
                        check = True
                        break 
                    
                    else:
                        pass
                    
                        
                #remove from KB but don't need to remove from possible_moves since we already did
                if check == True:
                    KB.remove(x)
                    continue
                
            '''
            #RANDOMPICK (OUR LAST RESORT)
            '''
            x = random.randint(0,len(possible_moves) - 1)
            print("recommended random move: ", possible_moves[x])
            i = int(input())
            j = int(input())
            agent_board, coord, clue = updateBoard((i,j), main_board, agent_board)
            
            if clue==9:
                print('MINE HIT AT:',coord)
            else:
                KB.append([coord, clue, len(checkNeighbors(possible_moves, coord))])
            
            possible_moves.remove(coord)
            print(agent_board)
            

    #NOT SURE WHAT WE WOULD RETURN HERE YET, IDEALLY WE WILL HAVE VISUALS ALONG THE WAY
    print(agent_board)
    print(main_board)
    return

In [211]:
Minesweeper(5,5)

[[0. 0. 2. 9. 9.]
 [1. 1. 2. 9. 3.]
 [9. 1. 1. 1. 1.]
 [1. 1. 0. 1. 1.]
 [0. 0. 0. 1. 9.]]
recommended random move:  (3, 3)
3
3
[[11. 11. 11. 11. 11.]
 [11. 11. 11. 11. 11.]
 [11. 11. 11. 11. 11.]
 [11. 11. 11.  1. 11.]
 [11. 11. 11. 11. 11.]]
recommended random move:  (3, 4)


KeyboardInterrupt: 