In [18]:
#Some imports
import numpy as np
import matplotlib.pyplot as plt
import random
import queue
import time

'''
Define the grid to be working with

**inputs:
dim = dimension size of the grid
n = number of mines

**returns:
board = the grid to be worked with
'''

def environment(dim, n):
    #start with a dim by dim zero array
    
    board = np.zeros((dim,dim))
    
    while n > 0:
        i = random.randint(0, dim - 1)
        j = random.randint(0, dim - 1)
        
        if board[i][j] == 9:
            pass
        else:
            board[i][j] = 9
            n -= 1
            
    for i in range(0, dim):
        for j in range(0, dim):
            if board[i][j] == 9:
                continue
            
            #check all the neighbors
            mines = 0
            rightValid = False
            leftValid = False
            upValid = False
            downValid = False
            if j - 1 >= 0:
                leftValid = True
            if j + 1 < len(board):
                rightValid = True
            if i + 1 < len(board):
                downValid = True
            if i - 1 >= 0:
                upValid = True
        
            #check left
            if leftValid == True:
                #check left adjacent
                if board[i][j-1] == 9:
                    #mine is here
                    mines += 1
                else:
                    #no mine is here
                    pass
                #check left & up
                if upValid == True:
                    if board[i-1][j-1] == 9:
                        #mine is here
                        mines += 1
                    else:
                        #no mine is here
                        pass           
                #check left & down
                if downValid == True:
                    if board[i+1][j-1] == 9:
                        #mine is here
                        mines += 1
                    else:
                        #no mine is here
                        pass
                        
            #check right
            if rightValid == True:
                #check right adjacent
                if board[i][j+1] == 9:
                    #mine is here
                    mines += 1
                else:
                    #no mine is here
                    pass
                #check right & up
                if upValid == True:
                    if board[i-1][j+1] == 9:
                        #mine is here
                        mines += 1
                    else:
                        #no mine is here
                        pass
                #check right & down
                if downValid == True:
                    if board[i+1][j+1] == 9:
                        #mine is here
                        mines += 1
                    else:
                        #no mine is here
                        pass
                        
            #check up adjacent
            if upValid == True:
                if board[i-1][j] == 9:
                    #mine is here
                    mines += 1
                else:
                    #no mine is here
                    pass
                    
            #check down adjacent
            if downValid == True:
                if board[i+1][j] == 9:
                    #mine is here
                    mines += 1
                else:
                    #no mine is here
                    pass
            
            board[i][j] = mines
    
    return board

In [26]:
'''
A Method to Check the Neighbors of a Cell

**inputs:
possible_moves = array of coordinates for the remaining moves
i = row
j = column

**returns:
board = the grid to be worked with
'''

#feed in the checking function the remaining possible moves, and it will easily return the neighbors
def checkNeighbors(possible_moves, i, j):
    neighbors = []
    if (i+1, j) in possible_moves:
        neighbors.append((i+1, j))
        
    if (i-1, j) in possible_moves:
        neighbors.append((i-1, j))
        
    if (i, j+1) in possible_moves:
        neighbors.append((i, j+1))
        
    if (i, j-1) in possible_moves:
        neighbors.append((i, j-1))
                          
    if (i+1, j+1) in possible_moves:
        neighbors.append((i+1, j+1))
                          
    if (i-1, j-1) in possible_moves:
        neighbors.append((i-1, j-1))
                          
    if (i+1, j-1) in possible_moves:
        neighbors.append((i+1, j-1))
                          
    if (i-1, j+1) in possible_moves:
        neighbors.append((i-1, j+1))
        
    return neighbors

In [ ]:
def updateBoard(coord, main_board, agent_board):
    i = coord[0]
    j = coord[1]
    agent_board[i][j] = main_board[i][j]
    return agent_board

In [39]:
'''
The Actual Game to be Played by our Agent

**inputs:
dim = dimension size of the grid
n = number of mines

**returns:

'''

def Minesweeper(dim, n):
    #create our main board and the board the agent will see
    main_board = environment(dim, n)
    agent_board = environment(dim, 0)
    
    #our three fringes, which make up our general knowledge base
    mineFringe = []
    safeFringe = []
    KB = []
    
    #populate a list of all the possible moves we can make, which will be edited later
    possible_moves = []
    for i in range(0, dim):
        for j in range(0, dim):
            possible_moves.append((i, j))
       
    #play until we finish the game
    gameFinished = False
    while gameFinished == False:
        code = 'goes here :)'
        #CHECK IF WE HAVE A SOLVED PUZZLE, I.E. IS LEN(POSSIBLE_MOVES) == 0?
        #IF SO BREAK
        
        
        #CHECK THE MINE FRINGE
        #FLAG A SPOT WITH 0.5 IF IT IS IN THE MINE FRINGE, THEN REMOVE IT FROM THE MINE FRINGE AND POSSIBLE_MOVES
        #IF NOTHING IS IN THE MINE FRINGE, PASS
        #CAN BE UPDATED EASILY WITH: mineFringe += checkNeighbors(possible_moves,1,0)
        
        
        #CHECK THE SAFE FRINGE
        #REVEAL A SPOT AND THEN REMOVE FROM THE SAFE FRINGE AND POSSIBLE_MOVES
        #IF NOTHING IS IN THE SAFE FRINGE, PASS
        #CAN BE UPDATED EASILY WITH: mineFringe += checkNeighbors(possible_moves,1,0)

        
        
        #CHECK THE KNOWLEDGE BASE (KB)
        #IF THE NUMBER OF MINES = THE NUMBER OF ADJACENT CELLS, CHECK THE NEIGHBORS AND ADD TO MINE FRINGE
        #IF THE NUMBER OF MINES = 0, CHECK THE NEIGHBORS AND ADD TO SAFE FRINGE
        #IF KB IS EMPTY, PASS
        #NO NEED TO USE CHECK NEIGHBOR FUNCTION HERE UNLESS WE ARE SURE TO ADD IT TO EITHER SAFE OR MINE FRINGE
        
        
        #RANDOMPICK (OUR LAST RESORT)
        #JUST CALL THE UPDATEBOARD FUNCTION TO OPEN A RANDOM COORDINATE IN POSSIBLE_MOVES
        #i = random.randint(0, len(POSSIBLE_MOVES) - 1) 
        #AGENT_BOARD = updateBoard(POSSIBLE_MOVES[i], MAIN_BOARD, AGENT_BOARD)
        #^^^^ THIS SHOULD UPDATE OUR AGENT BOARD FOR A RANDOM MOVE
        
        
    #NOT SURE WHAT WE WOULD RETURN HERE YET, IDEALLY WE WILL HAVE VISUALS ALONG THE WAY
    return

In [36]:
a = environment(10, 20)
b = environment(10, 0)
print(a)
print(b)
c = np.zeros((10,10))
for i in range(0, 10):
    for j in range(0, 10):
        c[i][j] = '*'

print(c)

[[0. 0. 0. 0. 1. 9. 9. 3. 1. 1.]
 [0. 0. 0. 0. 2. 4. 9. 3. 9. 2.]
 [0. 0. 0. 0. 1. 9. 2. 2. 2. 9.]
 [0. 0. 0. 1. 2. 2. 1. 0. 1. 1.]
 [1. 1. 0. 2. 9. 3. 1. 1. 1. 1.]
 [9. 2. 1. 3. 9. 9. 1. 2. 9. 3.]
 [9. 3. 2. 9. 4. 3. 3. 4. 9. 9.]
 [1. 2. 9. 2. 2. 9. 2. 9. 9. 3.]
 [0. 1. 1. 1. 1. 2. 3. 3. 2. 1.]
 [0. 0. 0. 0. 0. 1. 9. 1. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


ValueError: could not convert string to float: '*'